config/routes.rb
Rails.application.routes.draw do
  get "answers/summary"
  get "answers/about"
  devise_for :users
  root "answers#index"
  resources :answers
end

app/models/answer.rb
class Answer < ApplicationRecord
  validates :answer_1, presence: true
  validates :answer_2, presence: true
  validates :age, presence: true
  validates :country_code, presence: true

  self.per_page = 10

  def country_name
    country = ISO3166::Country[country_code]
    country.translations[I18n.locale.to_s] || country.name
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
    :recoverable, :rememberable, :validatable
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  def index
    @answer = Answer.new
  end

  def create
    @answer = Answer.new(answer_params)
    unless @answer.save
      render "index"
      return
    end
    redirect_to answers_summary_path
  end

  def summary
    @all_answer_1 = ""
    @all_answer_2 = ""
    # @answers = Answer.page(params[:page]).order("created_at DESC")
    @answers = Answer.all.order("created_at DESC")
    @all_answers = Answer.all

    @all_answers.each do |answer|
      @all_answer_1 += answer.answer_1 + " "
      @all_answer_2 += answer.answer_2 + " "
    end
    @all_answer_1 = @all_answer_1.gsub(/\r?\n/, ' ')
    @all_answer_2 = @all_answer_2.gsub(/\r?\n/, ' ')
    @all_answer_1 = @all_answer_1.gsub(/[^A-Za-z0-9]+/, ' ')
    @all_answer_2 = @all_answer_2.gsub(/[^A-Za-z0-9]+/, ' ')
  end

  def about
  end

  def destroy
    @answer = Answer.find(params[:id])
    @answer.destroy

    redirect_to answers_summary_path
  end

  private

  def answer_params
    params.require(:answer).permit(:answer_1, :answer_2, :age, :country_code)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/answers/index.html.erb
<h1 class="title">The End: A Hopeful Chapter of Life</h1>
<div class="book_wrapper">
    <a id="next_page_button"></a>
    <a id="prev_page_button"></a>
    <div id="loading" class="loading">Loading pages...</div>
    <div id="mybook" style="display:none;">
        <div class="b-load">
            <div class="div-wrapper">
                <h1>Share your thoughts!</h1>
                <p>1) Take a moment to reflect on the two questions on the right.</p>
                <p>2) Type up your answers in the boxes provided.</p>
                <p>3) Choose your age and location from the drop-down menu.</p>
                <p>4) Hit the “Submit” button at the bottom (both answers must be written in order to be submitted).</p>
                <p>5) You will be taken to the next page where you can see what other people around the world have shared!</p>
                <br>
                <p>- Click “<a href="/answers/summary">Results</a>” button on the top to see all the responses.</p>
                <p>- Click “<a href="/answers/about">About</a>” button on the top to know more about this project.</p>
                <br>

                <div style="text-align:center;">
                    <a href="https://www.facebook.com/hopefulchapteroflife" class="fa fa-facebook"></a>
                    <a href="https://www.instagram.com/hopefulchapteroflife" class="fa fa-instagram"></a>
                </div>

                <img src=<%= image_url("people_discussion.png") %> alt="" border="0px;" style="vertical-align: bottom"/>
            </div>
            <div>
                <%= form_with scope: :answer, url: answers_path, :html => {:id=>'form_id'}, local: true do |f| %>
                    <% if @answer.errors.any? %>
                        <div id="error_explanation">
                            <h2>
                                <%= pluralize(@answer.errors.count, "error") %>
                                prohibited your answer from being submitted:
                            </h2>
                            <ul>
                            <% @answer.errors.full_messages.each do |msg| %>
                                <li><%= msg %></li>
                            <% end %>
                            </ul>
                        </div>
                    <% end %>
                    <h1>1. What are your fears about end-of-life?</h1>
                    <%= f.text_area :answer_1, :class => "answer_text_field" %>
                    <br>
                    <br>
                    <br>
                    <h1>2. What legacy are you hoping to leave behind?</h1>
                    <%= f.text_area :answer_2, :class => "answer_text_field" %>
                    <br>
                    <br>
                    <br>
                    <h1>How old are you?</h1>
                    <%= f.select :age, (12..99), {}, {class: "answer_select_field"} %>
                    <br>
                    <br>
                    <br>
                    <h1>Where are you from?</h1>
                    <div class="answer_select_field">
                        <%= f.country_select :country_code, ([ "CA", "US" ]), iso_codes: true, id: :element_id %>
                    </div>
                    <br>
                    <br>
                    <br>
                    <%= link_to 'submit', "/answers", :onclick => "$('#form_id').submit()", :class => "demo" %>
                <% end %>
            </div>

            <%
=begin%>
 <div>
                <img src="/assets/4.jpg" alt="" />
                <h1>Bubbleriffic Image Gallery</h1>
                <p>In this tutorial we will create a bubbly image gallery that
                    shows your /assets in a unique way. The idea is to show the
                    thumbnails of albums in a rounded fashion allowing the
                    user to scroll them automatically by moving the mouse.
                    Clicking on a thumbnail will zoom in a big circle and
                    the full image which will be automatically resized to
                    fit into the screen.</p>
                <a href="http://tympanus.net/codrops/2010/12/10/bubbleriffic-image-gallery/" target="_blank" class="article">Article</a>
                <a href="http://tympanus.net/Tutorials/BubblerifficImageGallery/" target="_blank" class="demo">Demo</a>
            </div> 
<%
=end%>
        </div>
    </div>
</div>
<%
=begin%>
 <div>
    <span class="reference">
        <a href=" http://tympanus.net/codrops/2010/12/14/moleskine-notebook/">back to the Codrops tutorial</a>
        <a href="http://builtbywill.com/code/booklet/" target="_blank">booklet jQuery Plugin</a>
    </span>
</div> 
<%
=end%>

<!-- The JavaScript -->

<script type="text/javascript">
    $(function() {
        var $mybook 		= $('#mybook');
        var $bttn_next		= $('#next_page_button');
        var $bttn_prev		= $('#prev_page_button');
        var $loading		= $('#loading');
        var $mybook_assets	= $mybook.find('img');
        var cnt_assets		= $mybook_assets.length;
        var loaded			= 0;
        //preload all the /assets in the book,
        //and then call the booklet plugin

        $mybook_assets.each(function(){
            var $img 	= $(this);
            var source	= $img.attr('src');
            $('<img/>').load(function(){
                ++loaded;
                if(loaded == cnt_assets){
                    $loading.hide();
                    // $bttn_next.show();
                    // $bttn_prev.show();
                    $mybook.show().booklet({
                        name:               null,                            // name of the booklet to display in the document title bar
                        width:              1080,                             // container width
                        height:             665,                             // container height
                        speed:              600,                             // speed of the transition between pages
                        direction:          'LTR',                           // direction of the overall content organization, default LTR, left to right, can be RTL for languages which read right to left
                        startingPage:       0,                               // index of the first page to be displayed
                        easing:             'easeInOutQuad',                 // easing method for complete transition
                        easeIn:             'easeInQuad',                    // easing method for first half of transition
                        easeOut:            'easeOutQuad',                   // easing method for second half of transition

                        closed:             false,                           // start with the book "closed", will add empty pages to beginning and end of book
                        closedFrontTitle:   null,                            // used with "closed", "menu" and "pageSelector", determines title of blank starting page
                        closedFrontChapter: null,                            // used with "closed", "menu" and "chapterSelector", determines chapter name of blank starting page
                        closedBackTitle:    null,                            // used with "closed", "menu" and "pageSelector", determines chapter name of blank ending page
                        closedBackChapter:  null,                            // used with "closed", "menu" and "chapterSelector", determines chapter name of blank ending page
                        covers:             false,                           // used with  "closed", makes first and last pages into covers, without page numbers (if enabled)

                        pagePadding:        10,                              // padding for each page wrapper
                        pageNumbers:        true,                            // display page numbers on each page

                        hovers:             false,                            // enables preview pageturn hover animation, shows a small preview of previous or next page on hover
                        overlays:           false,                            // enables navigation using a page sized overlay, when enabled links inside the content will not be clickable
                        tabs:               false,                           // adds tabs along the top of the pages
                        tabWidth:           60,                              // set the width of the tabs
                        tabHeight:          20,                              // set the height of the tabs
                        arrows:             false,                           // adds arrows overlayed over the book edges
                        cursor:             'pointer',                       // cursor css setting for side bar areas

                        hash:               false,                           // enables navigation using a hash string, ex: #/page/1 for page 1, will affect all booklets with 'hash' enabled
                        keyboard:           false,                            // enables navigation with arrow keys (left: previous, right: next)
                        next:               $bttn_next,          			// selector for element to use as click trigger for next page
                        prev:               $bttn_prev,          			// selector for element to use as click trigger for previous page

                        menu:               null,                            // selector for element to use as the menu area, required for 'pageSelector'
                        pageSelector:       false,                           // enables navigation with a dropdown menu of pages, requires 'menu'
                        chapterSelector:    false,                           // enables navigation with a dropdown menu of chapters, determined by the "rel" attribute, requires 'menu'

                        shadows:            true,                            // display shadows on page animations
                        shadowTopFwdWidth:  166,                             // shadow width for top forward anim
                        shadowTopBackWidth: 166,                             // shadow width for top back anim
                        shadowBtmWidth:     50,                              // shadow width for bottom shadow

                        before:             function(){},                    // callback invoked before each page turn animation
                        after:              function(){}                     // callback invoked after each page turn animation
                    });
                    Cufon.refresh();
                }
            }).attr('src',source);
        });
				
    });
</script>

app/views/answers/summary.html.erb
<h1 class="title">The End: A Hopeful Chapter of Life</h1>
<div class="book_wrapper">
    <a id="next_page_button"></a>
    <a id="prev_page_button"></a>
    <div id="loading" class="loading">Loading pages...</div>
    <div id="mybook" style="display:none;">
        <div class="b-load">
            <div>
                <h1>1. What are your fears about end-of-life?</h1>
                <p>
                  This is a wordcloud of everyone's response!
                </p>
                <img src=<%= image_url("red-arrow.png") %> alt="" style="float:left; width:20%"/>
                <div 
                  id="wordCloud_1"
                  style="width:500px; 
                  height:500px; 
                  background-position:center;"></div>
            </div>
            <div style="overflow: scroll; height: 660px;">
                <h1>All Answers!</h1>
                <div style="text-align: center;">
                  <% @answers.each do |answer| %>
                    <div class="card">
                      <div class="answer_box"><p><%= answer.answer_1 %></p></div>
                      <p class="price" style="font-size: 18px"><%= answer.age%> / <%= answer.country_name %></p>
                      <% if user_signed_in? %>
                        <p><button>
                          <%= link_to 'Delete', answer_path(answer), method: :delete, data: { confirm: 'Are you sure?' }, :class => "card-link" %>
                        </button></p>
                      <% end %>
                    </div>
                  <% end %>
                </div>
            </div>
            <div>
                <h1>2. What legacy are you hoping to leave behind?</h1>
                <p>
                  This is a wordcloud of everyone's response!
                </p>
                <img src=<%= image_url("red-arrow.png") %> alt="" style="float:left; width:20%"/>
                <div 
                  id="wordCloud_2"
                  style="width:500px; 
                  height:500px; 
                  background-position:center;"></div>
            </div>
            <div style="overflow: scroll; height: 660px;">
                <h1>All Answers!</h1>
                <div style="text-align: center;">
                  <% @answers.each do |answer| %>
                    <div class="card">
                      <div class="answer_box"><p><%= answer.answer_2 %></p></div>
                      <p class="price" style="font-size: 18px"><%= answer.age%> / <%= answer.country_name %></p>
                      <% if user_signed_in? %>
                        <p><button>
                          <%= link_to 'Delete', answer_path(answer), method: :delete, data: { confirm: 'Are you sure?' }, :class => "card-link" %>
                        </button></p>
                      <% end %>
                    </div>
                  <% end %>
                </div>
            </div>
        </div>
    </div>
</div>

<!-- The JavaScript -->

<script>
 fetch("https://textvis-word-cloud-v1.p.rapidapi.com/v1/textToCloud", {
   method: "POST",
   headers: {
     "x-rapidapi-host": "textvis-word-cloud-v1.p.rapidapi.com",
     "x-rapidapi-key": "88e342cc0bmsh3054f62a586d151p132d3fjsn51ec7f3448ac",
     "content-type": "application/json",
     accept: "application/json"
   },
   body: JSON.stringify({
     text: "<%= @all_answer_1 %>",
     scale: 1,
     width: 500,
     height: 500,
     colors: ["#375E97", "#FB6542", "#FFBB00", "#3F681C"],
     font: "Tahoma",
     use_stopwords: true,
     language: "en",
     uppercase: false
   })
 })
   .then(response => {
     return response.text();
   })
   .then(wordCloud => {
     var img = document.getElementById("wordCloud_1");
     img.style.backgroundImage = "url(" + wordCloud + ")";
   })
   .catch(err => {
     console.log(err);
   });
</script>

<script>
 fetch("https://textvis-word-cloud-v1.p.rapidapi.com/v1/textToCloud", {
   method: "POST",
   headers: {
     "x-rapidapi-host": "textvis-word-cloud-v1.p.rapidapi.com",
     "x-rapidapi-key": "88e342cc0bmsh3054f62a586d151p132d3fjsn51ec7f3448ac",
     "content-type": "application/json",
     accept: "application/json"
   },
   body: JSON.stringify({
     text: "<%= @all_answer_2 %>",
     scale: 1,
     width: 500,
     height: 500,
     colors: ["#375E97", "#FB6542", "#FFBB00", "#3F681C"],
     font: "Tahoma",
     use_stopwords: true,
     language: "en",
     uppercase: false
   })
 })
   .then(response => {
     return response.text();
   })
   .then(wordCloud => {
     var img = document.getElementById("wordCloud_2");
     img.style.backgroundImage = "url(" + wordCloud + ")";
   })
   .catch(err => {
     console.log(err);
   });
</script>

<script type="text/javascript">
    $(function() {
        var $mybook 		= $('#mybook');
        var $bttn_next		= $('#next_page_button');
        var $bttn_prev		= $('#prev_page_button');
        var $loading		= $('#loading');
        var $mybook_assets	= $mybook.find('img');
        var cnt_assets		= $mybook_assets.length;
        var loaded			= 0;
        //preload all the /assets in the book,
        //and then call the booklet plugin

        $mybook_assets.each(function(){
            var $img 	= $(this);
            var source	= $img.attr('src');
            $('<img/>').load(function(){
                ++loaded;
                if(loaded == cnt_assets){
                    $loading.hide();
                    $bttn_next.show();
                    $bttn_prev.show();
                    $mybook.show().booklet({
                        name:               null,                            // name of the booklet to display in the document title bar
                        width:              1080,                             // container width
                        height:             665,                             // container height
                        speed:              600,                             // speed of the transition between pages
                        direction:          'LTR',                           // direction of the overall content organization, default LTR, left to right, can be RTL for languages which read right to left
                        startingPage:       0,                               // index of the first page to be displayed
                        easing:             'easeInOutQuad',                 // easing method for complete transition
                        easeIn:             'easeInQuad',                    // easing method for first half of transition
                        easeOut:            'easeOutQuad',                   // easing method for second half of transition

                        closed:             false,                           // start with the book "closed", will add empty pages to beginning and end of book
                        closedFrontTitle:   null,                            // used with "closed", "menu" and "pageSelector", determines title of blank starting page
                        closedFrontChapter: null,                            // used with "closed", "menu" and "chapterSelector", determines chapter name of blank starting page
                        closedBackTitle:    null,                            // used with "closed", "menu" and "pageSelector", determines chapter name of blank ending page
                        closedBackChapter:  null,                            // used with "closed", "menu" and "chapterSelector", determines chapter name of blank ending page
                        covers:             false,                           // used with  "closed", makes first and last pages into covers, without page numbers (if enabled)

                        pagePadding:        10,                              // padding for each page wrapper
                        pageNumbers:        true,                            // display page numbers on each page

                        hovers:             false,                            // enables preview pageturn hover animation, shows a small preview of previous or next page on hover
                        overlays:           false,                            // enables navigation using a page sized overlay, when enabled links inside the content will not be clickable
                        tabs:               false,                           // adds tabs along the top of the pages
                        tabWidth:           60,                              // set the width of the tabs
                        tabHeight:          20,                              // set the height of the tabs
                        arrows:             false,                           // adds arrows overlayed over the book edges
                        cursor:             'pointer',                       // cursor css setting for side bar areas

                        hash:               false,                           // enables navigation using a hash string, ex: #/page/1 for page 1, will affect all booklets with 'hash' enabled
                        keyboard:           true,                            // enables navigation with arrow keys (left: previous, right: next)
                        next:               $bttn_next,          			// selector for element to use as click trigger for next page
                        prev:               $bttn_prev,          			// selector for element to use as click trigger for previous page

                        menu:               null,                            // selector for element to use as the menu area, required for 'pageSelector'
                        pageSelector:       false,                           // enables navigation with a dropdown menu of pages, requires 'menu'
                        chapterSelector:    false,                           // enables navigation with a dropdown menu of chapters, determined by the "rel" attribute, requires 'menu'

                        shadows:            true,                            // display shadows on page animations
                        shadowTopFwdWidth:  166,                             // shadow width for top forward anim
                        shadowTopBackWidth: 166,                             // shadow width for top back anim
                        shadowBtmWidth:     50,                              // shadow width for bottom shadow

                        before:             function(){},                    // callback invoked before each page turn animation
                        after:              function(){}                     // callback invoked after each page turn animation
                    });
                    Cufon.refresh();
                }
            }).attr('src',source);
        });
				
    });
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "https://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html>
  <head>
    <title>A Hopeful Chapter of Life</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1">

  	<script type="text/javascript" src="https://code.jquery.com/jquery-2.2.4.min.js"></script>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag 'jquery.booklet.1.1.0.css', media: 'all', 'data-turbolinks-track': 'reload' %>

	  <script type="text/javascript">
		  Cufon.replace('h1,p,.b-counter');
		  Cufon.replace('.book_wrapper a', {hover:true});
		  // Cufon.replace('.title', {textShadow: '1px 1px #C59471', fontFamily:'Ink Journal Regular'});
		  // Cufon.replace('.reference a', {textShadow: '1px 1px #C59471', fontFamily:'Ink Journal Regular'});
		  // Cufon.replace('.loading', {textShadow: '1px 1px #000', fontFamily:'Ink Journal Regular'});
	  </script>

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
  </head>

  <body>
    <% if notice %>
      <p class="alert alert-success"><%= notice %></p>
    <% end %>
    <% if alert %>
      <p class="alert alert-danger"><%= alert %></p>
    <% end %>

    <div class="navbar">
      <a class="active" href="/"><i class="fa fa-fw fa-home"></i> Home</a>
      <a href="/answers/about"><i class="fa fa-fw fa-user"></i> About</a>
      <a href="/answers/summary"><i class="fa fa-fw fa-search"></i> Results</a>
      <a href="mailto:hopefulchapteroflife@gmail.com"><i class="fa fa-fw fa-envelope"></i> Contact Us</a>

      <% if user_signed_in? %>
        <a href="/users/edit"><i class="fa fa-fw fa-user"></i> Edit</a>
        <a href="/users/sign_out" data-method="delete"><i class="fa fa-fw fa-user"></i> Sign Out</a>
      <% end %>
    </div>
    <%= yield %>
  </body>
</html>